### ISSUE TITLE
Assignment 3

### ISSUE THREAD

**Issue by DharminB** [HBRS-MAAS/ws18-project-right-brothers#15]
- Update your agent definitions. You should have the entire workflow modeled by now, including behaviors (and their type) and the messages exchanged by the agents (and their type). **Don't forget to open a pull request with your order messages**.
  - Your architecture should be uploaded both to LEA and the docs folder of your repository
  - The architecture should be considered documentation, i.e. while the diagram helps visualize, you should provide explanations as to why you took the decisions you took.
  - Add the agent/object which will manage the common time between your agents, and describe how it will work.
- Make sure you can parse the sample scenario, found in config/sample, that is in the upstream remote (https://github.com/HBRS-MAAS/project/tree/master/src/main/resources/config/sample) and generate the required agents and objects
  - Test sending the customer order read from the sample file to the order processing agent.
- Add a visualization.md file with your proposal of what and how would you visualize the project, and which library or framework fits best your requirements. Upload it as a PDF to LEA.
  - This will be a shared agent between all teams in the course, therefore **make a pull request to the upstream remote!**
- Create the skeletons for all the agents in your workflow and set up basic communication between them based on your message definitions.
  - focus on the common agents that will serve as interfaces between the different stages (see the attached image for hints)
    - proofer
    - cooling racks
    - loading bay
    - mailbox

NOTES:

- Please keep your repositories up to date with the upstream remote (you should regularly check if there have been changes). Be careful when you merge and take a look at what the changes do. Open GitHub issues for any questions, problems or suggestions you're having.
- Use markdown formatting properly!
![production-stages](https://user-images.githubusercontent.com/17234248/48140791-ce1a9880-e2a9-11e8-8605-e49b2bb1abc7.png)

**Comment by ZahidSE** [comment]
I would like to work on the parsing task (2) along with creating all the required model/object classes.

Also you can assign more tasks.

**Comment by DharminB** [comment]
Aw, man. I already started working on that. But anyway that is a big question, so maybe we both can work on it. We then have to divide that into smaller parts

**Comment by ZahidSE** [comment]
:-) ok I will just check if there is any simpler way to read the input file. If I find one I will notify you.

I will then work on 4 (skeleton). But that will depend on task 1. Do you think we should sit together for task 1.

**Comment by DharminB** [comment]
We could if that is more productive

**Comment by DRealArun** [comment]
I have assigned the visualization task to me.

**Comment by DRealArun** [comment]
Visualization.md Pull request : https://github.com/HBRS-MAAS/project/pull/17
