### ISSUE TITLE
design and documentation

### ISSUE THREAD

**Issue by DharminB** [HBRS-MAAS/ws18-project-right-brothers#17]
- [x] Update your agent definitions. You should have the entire workflow modeled by now, including behaviors (and their type) and the messages exchanged by the agents (and their type). 
- [x] **Don't forget to open a pull request with your order messages**.
  - [x] Your architecture should be uploaded both to LEA and the docs folder of your repository
  - [x] The architecture should be considered documentation, i.e. while the diagram helps visualize, you should provide explanations as to why you took the decisions you took.
  - [x] Add the agent/object which will manage the common time between your agents,
  - [x] Describe how it (clock) will work.

**Comment by DharminB** [comment]
@DRealArun could take care of the remaining things in this issue?

**Comment by DRealArun** [comment]
Was waiting for you to merge the previous pull request to develop. I will update now

**Comment by DharminB** [comment]
I was the one who created previous merge request. I thought one of you guys would check and merge that pull. I guess, there should be a convention set for this so that this dependency and confusion does not occur again.

**Comment by DRealArun** [comment]
I think a pull request for the message.md to the upstream repository also needs to be created . Please correct me if I am wrong @DharminB , @ZahidSE
