### ISSUE TITLE
Skeleton code doubt

### ISSUE THREAD

**Issue by DharminB** [HBRS-MAAS/ws18-project-right-brothers#24]
@argenos 
1. Is the design of the project already chosen? Since we did not have a class last wednesday for discussing and debating about the best design for creating agents and their conversations, we were wondering if the design has been finalised or not.
2. If it is not finalised, it does not seem possible to implement the skeleton code for the connectors of different stages (proofer, cooling racks, etc) and test it. If we implement agents based on our design, and unfortunately that design is not chosen then our agents will not be able to talk to agents created by other teams.

**Comment by argenos** [comment]
> Is the design of the project already chosen? Since we did not have a class last wednesday for discussing and debating about the best design for creating agents and their conversations, we were wondering if the design has been finalised or not.
It is not, but we (those who stayed) agreed last class that everyone would implement the skeletons of the interface agents, and the best ones would be merged into the upstream. 
> If it is not finalised, it does not seem possible to implement the skeleton code for the connectors of different stages (proofer, cooling racks, etc) and test it. If we implement agents based on our design, and unfortunately that design is not chosen then our agents will not be able to talk to agents created by other teams.
That is exactly the point! I want the interface agents along with their messages (incoming and outgoing) to be thought out. Depending on the quality of the proposal, the accepted pull requests will receive extra points.

More importantly, those skeleton agents for now don’t need to perform *all* their functionalities, but should at least be able to receive their incoming message and output a reasonable outgoing message.
