### ISSUE TITLE
Mechanism for synchronization of read/writes to the shared file which is used by the visualization agent. 

### ISSUE THREAD

**Issue by DRealArun** [HBRS-MAAS/ws18-project-right-brothers#31]
We need to discuss about our strategy to synchronize the file operations of the multiple agents when they try to write their status to the shared file (which will be used by the visualization agent). One direction to look into would be to add a status update behavior to all the agents which waits on a semaphore/mutex to update its most recent status to the file.

**Comment by DharminB** [comment]
A multi agent way would be to have an agent specifically doing this. All agents send INFORM message to this agent. This agent will have a cyclic behaviour to perform the writing to a text file task. 

Preferable we would want to use the builtin `gui` tool. I think sniffer or something. This idea (writing to a file) would only we our choice if we have to visualise in a setup without Xwindows.
