### ISSUE TITLE
PDF file

### ISSUE THREAD

**Issue by DharminB** [HBRS-MAAS/ws18-project-right-brothers#5]
- Your team must upload your architecture and the agent definitions as discussed today, including the messages exchanged between agents. Keep in mind scalability! You may have thousands of any given property of the bakery, whether it be orders, ovens, trucks or customers. Make sure you are clear about which parts should be:
  - agents
    - is it created at runtime or at startup?
    - what behaviors does it have?
  - objects
- To which stage do these agents belong?
- Add the architecture diagram to your docs folder
- How do you plan to aggregate order data? Include a list of possible options, and which agent would take care of this.

**Comment by DharminB** [comment]
Please add a section regarding _aggregating order data_ @DRealArun

**Comment by DharminB** [comment]
Also after all issues are resolved, please upload the pdf file to lea

**Comment by DRealArun** [comment]
I have updated the pdf. Kindly review it and upload to lea if everything is found OK !
