### ISSUE TITLE
Pack products according to the orders

### ISSUE THREAD

**Issue by DharminB** [HBRS-MAAS/ws18-project-right-brothers#52]
- [x] get products with quantity from agent from #51 
- [x] match each product with the order (based on delivery date emergency)
- [x] create box objects for individual products
- [ ] pack the order according to their priority

**Comment by DRealArun** [comment]
@ZahidSE  : This Loading bay agent expects products after post processing as input. The agent then packs it and then maps it to the orders and then sends the message in the above mentioned format to the transport stage.

**Comment by ZahidSE** [comment]
@DRealArun, The proposed message is fine. [Output message from Loading bay](https://github.com/HBRS-MAAS/project/issues/31). We would need to consider **breadsPerBox** (bakeries.json) too.

**For transport and delivery, products are boxed. For each product, a certain number of items fit into a box. Only items of same kind in a box.**
