### ISSUE TITLE
multi computer execution

### ISSUE THREAD

**Issue by DharminB** [HBRS-MAAS/ws18-project-right-brothers#6]
Test your customer and processing agent in different computers.

**Comment by DRealArun** [comment]
**Current Status :** 

- We tried to setup the multi-agent on different computer approach using a router.
- We were able to connect to the router, however we could not setup the router to have internet access.
- We attempted to run the customer on one machine and seller on another machine but the gradle run fails as it needs to access the internet for some reason.
- Need to debug further.

**Comment by ZahidSE** [comment]
@DharminB I tried again today and it works now. You will find the instruction on how to run it from multiple machines in README. I have sent a merge request to the branch. I have made several changes on top of your work in "Added customer baker" branch. Can you please review the changes and accept the pull request.
