### ISSUE TITLE
Use org.maas.Start instead of org.right_brothers.Start

### ISSUE THREAD

**Issue by ZahidSE** [HBRS-MAAS/ws18-project-right-brothers#70]
- [x] Make use of the upstream version of Start

- [ ] Remove the current Start file after switching

**Comment by DharminB** [comment]
I am not removing out version of Start.java because of safety purpose. It could at a later point in time be used as a backup start file. Also visualisation and packaging stage are not concrete at the moment and thus I want to keep the old file for ease of lookup and quick debugging. @ZahidSE
