### ISSUE TITLE
Everything on same page

### ISSUE THREAD

**Issue by DharminB** [HBRS-MAAS/ws18-project-right-brothers#9]
The names of the messages in the `.md` file and the `pdf` file do not match. Could you guys (@DRealArun 
 and @ZahidSE ) discuss among yourself and change one of the file accordingly.

The names of messages in `.md` file are in headings and the names of the messages in `pdf` file are in the bullet point **message in** and **message out**.

**Comment by DRealArun** [comment]
I think it is easier to change the .md file. What do you feel @ZahidSE ?

**Comment by DRealArun** [comment]
I have made changes. Kindly verify and merge.

**Comment by ZahidSE** [comment]
@DRealArun  :-( Sorry bro, I missed this notification. Indeed changing md file could be easier instead of changing all 3 files.
